### ISSUE TITLE
Why the double transpose?

### ISSUE THREAD

**Issue by jovsa** [malhotraa/transformer-experiments#6]
I noticed there was a `transpose(1,2)` [HERE](https://github.com/malhotraa/transformer-experiments/blob/main/transformer/pytorch/model.py#L198-L200) and another `transpose(1,2)` [HERE](https://github.com/malhotraa/transformer-experiments/blob/main/transformer/pytorch/model.py#L206).

Looks like these two `transpose(1,2)` negate each other. Any idea why they are there?

**Comment by malhotraa** [comment]
I think its because `attention` module expects q, k, v matrices to be in following order of dims:
(batch_size, num_heads, seq_len_q, d_h)
To understand why this is the case you have to examine the code in the attention module:
```
    scores = torch.matmul(query, key.transpose(-2, -1)) / math.sqrt(d_k)
```
This line is expecting the last two dims in key to be seq_len, d_h.

**Comment by jovsa** [comment]
thanks
